import {
  BookOpenIcon,
  BotIcon,
  BrainIcon,
  BriefcaseIcon,
  CameraIcon,
  ChartLineIcon,
  CloudIcon,
  CodeIcon,
  CpuIcon,
  DatabaseIcon,
  FileTextIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadsetIcon,
  HeartIcon,
  LightbulbIcon,
  type LucideIcon,
  MessageCircleIcon,
  MusicIcon,
  PaletteIcon,
  PenLineIcon,
  RocketIcon,
  ScaleIcon,
  ShieldIcon,
  SparklesIcon,
  TargetIcon,
  WalletIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";

/** Central icon-name → lucide-component registry (agents, skills, chats). */
export const AGENT_ICON_REGISTRY: Record<string, LucideIcon> = {
  book: BookOpenIcon,
  bot: BotIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  camera: CameraIcon,
  chart: ChartLineIcon,
  cloud: CloudIcon,
  code: CodeIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  file: FileTextIcon,
  globe: GlobeIcon,
  graduation: GraduationCapIcon,
  headset: HeadsetIcon,
  heart: HeartIcon,
  lightbulb: LightbulbIcon,
  message: MessageCircleIcon,
  music: MusicIcon,
  palette: PaletteIcon,
  pen: PenLineIcon,
  rocket: RocketIcon,
  scale: ScaleIcon,
  shield: ShieldIcon,
  sparkles: SparklesIcon,
  target: TargetIcon,
  wallet: WalletIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
};

export function resolveAgentIcon(name?: string | null): LucideIcon {
  return (name && AGENT_ICON_REGISTRY[name]) || SparklesIcon;
}
